# Generated by Django 4.0.1 on 2022-01-20 22:06

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buysellindicator', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], help_text='A value of BUY for buys, SELL for sells', max_length=4)),
                ('price', models.FloatField(help_text='The price of the Trade')),
                ('quantity', models.IntegerField(help_text='The amount of units traded')),
            ],
            options={
                'verbose_name': 'Trade Detail',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_Class', models.CharField(default=None, help_text='The asset class of the instrument traded. E.g. Bond, Equity, FX...etc', max_length=60, verbose_name='assetClass')),
                ('counterparty', models.CharField(default=None, help_text='The counterparty the trade was executed with. May not always be available', max_length=100)),
                ('instrument_Id', models.CharField(help_text='The ISIN/ID of the instrument traded. E.g. TSLA, AAPL, AMZN...etc', max_length=10, unique=True, verbose_name='instrumentId')),
                ('instrument_Name', models.CharField(help_text='The name of the instrument traded', max_length=20, verbose_name='instrumentName')),
                ('trader', models.CharField(help_text='The name of the Trader', max_length=100)),
                ('trade_date_time', models.DateTimeField(help_text='The date-time the Trade was executed', verbose_name='tradeDateTime')),
                ('trade_id', django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, populate_from=['instrument_Id', 'trader'], verbose_name='tradeId')),
                ('trade_details', models.ForeignKey(help_text='The details of the trade, i.e. price, quantity', on_delete=django.db.models.deletion.CASCADE, to='Trades.tradedetails', verbose_name='tradeDetais')),
            ],
            options={
                'ordering': ['instrument_Name'],
                'get_latest_by': 'trade_date_time',
            },
        ),
    ]
