# Generated by Django 4.0.1 on 2022-01-20 23:28

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Trades', '0002_remove_trade_trade_details_tradedetails_trade_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradedetails',
            name='trade_item',
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_details',
            field=models.OneToOneField(default=None, help_text='The details of the trade, i.e. price, quantity', on_delete=django.db.models.deletion.CASCADE, to='Trades.tradedetails', verbose_name='tradeDetails'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='instrument_Id',
            field=models.CharField(help_text='The ISIN/ID of the instrument traded. E.g. TSLA, AAPL, AMZN...etc', max_length=10, verbose_name='instrumentId'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['instrument_Id', 'trader'], unique=True, verbose_name='tradeId'),
        ),
    ]
